---
- name: Deploy a complete log management stack (central server)
  hosts: localhost
  become: yes
  vars:
    elasticsearch_version: "7.x"
    IP_DU_SERVEUR_CENTRAL: "{{ ansible_default_ipv4.address }}"

  tasks:
    - name: Ensure prerequisites are installed
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - openjdk-11-jre
        - gnupg2
        - ca-certificates
        - curl

    - name: Add Fluentd GPG Key and Repository
      apt_key:
        url: https://packages.treasuredata.com/GPG-KEY-td-agent
        state: present

    - name: Add Fluentd repository
      apt_repository:
        repo: "deb [trusted=yes] https://packages.treasuredata.com/3/ubuntu/bionic/ bionic contrib"
        state: present

    - name: Ensure Rsyslog is installed and started
      apt:
        name: rsyslog
        state: present
      notify:
        - Restart Rsyslog

    - name: Configure Rsyslog to receive logs from other servers
      lineinfile:
        path: /etc/rsyslog.conf
        state: present
        line: "{{ item }}"
      with_items:
        - '$ModLoad imudp'
        - '$UDPServerRun 514'
        - '$ModLoad imtcp'
        - '$InputTCPServerRun 514'
      notify:
        - Restart Rsyslog

    - name: Ensure Logrotate is installed
      apt:
        name: logrotate
        state: present

    - name: Install Fluentd (td-agent)
      apt:
        name: td-agent
        state: present
      notify:
        - Restart Fluentd

    - name: Install Elasticsearch GPG Key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elasticsearch repository
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/apt stable main"
        state: present
        filename: elasticsearch

    - name: Install Elasticsearch
      apt:
        name: elasticsearch
        state: present
      notify:
        - Restart Elasticsearch

    - name: Install Kibana
      apt:
        name: kibana
        state: present
      notify:
        - Restart Kibana

  handlers:
    - name: Restart Rsyslog
      systemd:
        name: rsyslog
        state: restarted

    - name: Restart Fluentd
      systemd:
        name: td-agent
        state: restarted

    - name: Restart Elasticsearch
      systemd:
        name: elasticsearch
        state: restarted

    - name: Restart Kibana
      systemd:
        name: kibana
        state: restarted
