---
- name: Deploy a complete log management stack
  hosts: all
  become: yes
  vars:
    graylog_password_secret: "{{ lookup('password', '/dev/null length=96') }}"
    graylog_root_password_sha2: "{{ 'password' | password_hash('sha512') }}"
    elasticsearch_version: "7.x"

  tasks:

    - name: Ensure prerequisites are installed
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - openjdk-11-jre
        - gnupg2
        - ca-certificates
        - curl

    # ----------- Rsyslog Installation and Configuration ----------
    - name: Ensure Rsyslog is installed
      apt:
        name: rsyslog
        state: present
        update_cache: yes

    - name: Ensure Rsyslog is enabled and started
      systemd:
        name: rsyslog
        enabled: yes
        state: started

    # ----------- Logrotate Installation ----------
    - name: Ensure Logrotate is installed
      apt:
        name: logrotate
        state: present

    # ----------- Fluentd Installation ----------
    - name: Install Fluentd (td-agent)
      apt:
        name: td-agent
        state: present
        update_cache: yes

    - name: Ensure Fluentd is enabled and started
      systemd:
        name: td-agent
        enabled: yes
        state: started

    # ----------- Elasticsearch Installation ----------
    - name: Install Elasticsearch GPG Key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elasticsearch repository
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/apt stable main"
        state: present
        filename: elasticsearch

    - name: Install Elasticsearch
      apt:
        name: elasticsearch
        state: present
        update_cache: yes

    - name: Ensure Elasticsearch is enabled and started
      systemd:
        name: elasticsearch
        enabled: yes
        state: started

    # ----------- Graylog Installation ----------
    - name: Install Graylog repository
      apt_repository:
        repo: 'deb https://packages.graylog2.org/repo/packages/graylog/4.x/ubuntu/ stable main'
        state: present

    - name: Install Graylog
      apt:
        name: graylog-server
        state: present
        update_cache: yes

    - name: Configure Graylog Server
      lineinfile:
        path: /etc/graylog/server/server.conf
        state: present
        line: "{{ item }}"
      with_items:
        - "password_secret = {{ graylog_password_secret }}"
        - "root_password_sha2 = {{ graylog_root_password_sha2 }}"
        - "http_bind_address = 0.0.0.0:9000"

    - name: Ensure Graylog is enabled and started
      systemd:
        name: graylog-server
        enabled: yes
        state: started

    # ----------- Kibana Installation ----------
    - name: Install Kibana
      apt:
        name: kibana
        state: present
        update_cache: yes

    - name: Ensure Kibana is enabled and started
      systemd:
        name: kibana
        enabled: yes
        state: started
