---
- name: Deploy a complete log management stack
  hosts: all
  become: yes
  vars:
    graylog_password_secret: "{{ lookup('password', '/dev/null length=96') }}"
    graylog_root_password_sha2: "{{ 'password' | password_hash('sha512') }}"
    elasticsearch_version: "7.x"

  tasks:
    - name: Ensure prerequisites are installed
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - openjdk-11-jre
        - gnupg2
        - ca-certificates
        - curl

    - name: Ensure Rsyslog is installed and started
      apt:
        name: rsyslog
        state: present
      notify:
        - Start Rsyslog

    - name: Ensure Logrotate is installed
      apt:
        name: logrotate
        state: present

    - name: Install Fluentd (td-agent)
      apt:
        name: td-agent
        state: present
      notify:
        - Start Fluentd

    - name: Install Elasticsearch GPG Key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elasticsearch repository
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/apt stable main"
        state: present
        filename: elasticsearch

    - name: Install Elasticsearch
      apt:
        name: elasticsearch
        state: present
      notify:
        - Start Elasticsearch

    - name: Install Graylog repository
      apt_repository:
        repo: 'deb https://packages.graylog2.org/repo/packages/graylog/4.x/ubuntu/ stable main'
        state: present

    - name: Install Graylog
      apt:
        name: graylog-server
        state: present

    - name: Configure Graylog Server
      lineinfile:
        path: /etc/graylog/server/server.conf
        state: present
        line: "{{ item }}"
      with_items:
        - "password_secret = {{ graylog_password_secret }}"
        - "root_password_sha2 = {{ graylog_root_password_sha2 }}"
        - "http_bind_address = 0.0.0.0:9000"
      notify:
        - Start Graylog
    
    - name: Install Kibana
      apt:
        name: kibana
        state: present
      notify:
        - Start Kibana

  handlers:
    - name: Start Rsyslog
      systemd:
        name: rsyslog
        enabled: yes
        state: started

    - name: Start Fluentd
      systemd:
        name: td-agent
        enabled: yes
        state: started

    - name: Start Elasticsearch
      systemd:
        name: elasticsearch
        enabled: yes
        state: started

    - name: Start Graylog
      systemd:
        name: graylog-server
        enabled: yes
        state: started
      when: "'elasticsearch' in (ansible_facts.services|default({})).keys() and (ansible_facts.services.elastic_search.state|default('inactive') == 'running')"
      
    - name: Start Kibana
      systemd:
        name: kibana
        enabled: yes
        state: started
